### PR TITLE
feature: add preference to control double click (+ctrl) on node behavior

### PR DESCRIPTION
**Pull request by stockbal**
Hi @fidley ,

fingers crossed that you haven't been working on this issue yet :). I just had the urge to play a little around. At the end I did a view more changes than I planned 😛.

Regards
Ludwig

List of changes
- Separate action class to encapsulate "double click"/"Enter press" action
- Separate class to handle event registration for node double click /
  enter key event
- enable opening multiple objects at once during "double click" action
  as well as in "open in project" action
- refactoring of run/open logic into separate class

#59

### CODE REVIEW

**Comment by fidley** [comment]
Wow @stockbal , really nice! I haven't do much with it, so it's really good that you had time for it.

I'll quickly look on this before merging. Thanks for contribution!

**Comment by fidley** [comment]
Works like a charm! Thanks! I will update the plugin update site today. Do you have a twitter handle?

**Comment by fidley** [comment]
And congratulation for begin able to read my ugly Java code :)

**Comment by stockbal** [comment]
> Works like a charm! Thanks! I will update the plugin update site today. Do you have a twitter handle?

Happy to hear that 😄. Unfortunately I don't have a Twitter account. Up until now I did not see a reason to create one 😉.

**Comment by fidley** [comment]
Haha, Ok, then I will give credits about this in other way :)

**Pull request merged**
